version: 2.1
jobs:
  build-and-push:
    environment:
      IMAGE_NAME: std4453/mikanarr
      IMAGE_VERSION: 1.1.3
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build Docker image
          command: |
            docker build . \
              -t std4453/mikanarr:latest \
              -t std4453/mikanarr:$IMAGE_VERSION
      - run:
          name: Push image to Docker Hub
          command: |
            echo "$DOCKERHUB_ACCESS_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$IMAGE_VERSION
workflows:
  commit:
    jobs:
      - build-and-push:
          context:
            - docker-hub
          filters:
            branches:
              only: master
